server:
  host: raspberrypi
  port: 8086
  user: admin
  password: UEPVwPC4KNv9ZGyx4qJE

database:
  drop: no
  name: myhome

import:
  path: C:\Users\mathew\Desktop #C:\Users\mathew\OneDrive\PV-Anlage\_Messdaten\Winsol

# enable debugging and log in path
debug:
  active: no
  path: /tmp
